project:
  type: website
  output-dir: "a3eced31e4ca8c5ae5b58a0948b44dc319c9ae7ac"
  execute-dir: project
  resources:
    - "/www/"
    - "/CNAME"

website:
  title: "Yanjik&Aleni JG*inA"
  navbar:
    left:
      - href: index.qmd
        text: Startseite
        icon: house
      - href: program/index.qmd
        text: Programm
      - href: info/about.qmd
        text: Informationen
  page-footer:
    right: "Bestewochenen.de"
    left: "© 2025, Patrick Altmeyer & Daniëlle Kotter"

lang: de

format:
  html:
    include-in-header: 
      - text: |
          <script>
          window.addEventListener('load', () => {history.replaceState(null, null, "/");});
          </script>
    theme:
      - theme-light.scss
      - brand
    toc: true
